name: Docker image CI for ghcr

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u robenn11 --password-stdin
      - name: Build and push the image with commit SHA tag
        run: |
          docker build . -t ghcr.io/robenn11/aquaman:${GITHUB_SHA::7}
          docker push ghcr.io/robenn11/aquaman:${GITHUB_SHA::7}

  publish_tagged_image:
    needs: build_and_publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u robenn11 --password-stdin
      - name: Build and push the image with tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          docker build . -t ghcr.io/robenn11/aquaman:${TAG_NAME}
          docker push ghcr.io/robenn11/aquaman:${TAG_NAME}
